PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX ex: <https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
ASK { ?phim a dbo:Film ; ex:title "Inception" ; owl:sameAs <http://www.wikidata.org/entity/Q25188> }
