PREFIX ex: <https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/ontology#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX res: <https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?s ?label WHERE { ?s a dbo:Agent . FILTER EXISTS { ?s a dbo:Person } FILTER(STRSTARTS(STR(?s), "https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/resource/")) OPTIONAL { ?s rdfs:label ?label } } ORDER BY ?s
