# -*- coding: utf-8 -*-
"""24-slide Vietnamese presentation; genuine screenshots and explicit Protégé photo slots."""
from pathlib import Path
import json
from common import ROOT

PROTEGE_SHOTS = {
 'P00': {'file':'P00_ontology_header.png','title':'Ontology IRI và phiên bản','owl':'Movie_Ontology.owl','steps':['Mở ontology/Movie_Ontology.owl.','Chọn Active Ontology / Ontology Header.','Giữ IRI ontology và versionInfo 2.0.0 trong khung hình.'],'expect':'IRI đúng namespace của bài; phiên bản 2.0.0. Metrics có thể tính cả lớp ngoài được tham chiếu, khác 42 lớp tự khai báo.'},
 'P01': {'file':'P01_film_hierarchy.png','title':'Cây lớp phim','owl':'Movie_Ontology.owl','steps':['Entities → Classes → mở CreativeWork và Film.','Hiện các lớp con FeatureFilm, AnimatedFilm và nhóm phim.','Chọn Film; giữ IRI DBpedia và Class Description.'],'expect':'Film thuộc CreativeWork; IRI là http://dbpedia.org/ontology/Film. Chụp cây khai báo, không gọi là cây đã suy luận.'},
 'P02': {'file':'P02_agent_hierarchy.png','title':'Cây người và tổ chức','owl':'Movie_Ontology.owl','steps':['Entities → Classes → mở Agent.','Mở Person và Organization → ProductionCompany.','Chọn Person hoặc Filmmaker; giữ cây lớp và Description.'],'expect':'Person và Organization cùng dưới Agent; Actor/Filmmaker/AwardWinner là lớp con Person.'},
 'P03': {'file':'P03_genre_award_hierarchy.png','title':'Cây Genre và Award','owl':'Movie_Ontology.owl','steps':['Thu gọn Film/Agent để ảnh dễ đọc.','Mở Genre → FictionGenre / NonFictionGenre và Award.','Hiện các lớp thể loại và nhóm giải; giữ Class Description.'],'expect':'Cây Genre/Award khớp sơ đồ. Nhóm thể loại/giải được ánh xạ theo nhãn trong bước build.'},
 'P04': {'file':'P04_contribution_restrictions.png','title':'Ràng buộc của Contribution','owl':'Movie_Ontology.owl','steps':['Entities → Classes → chọn Contribution.','Trong Class Description, mở đủ SubClass Of.','Hiện contributionBy / contributionTo / hasRole: exactly 1.'],'expect':'Ba qualified cardinality đúng 1, cùng các allValuesFrom. Đây là mô hình OWL, không phải biên bản kiểm tra thiếu trường.'},
 'P05': {'file':'P05_object_property.png','title':'Domain, range, inverse, functional','owl':'Movie_Ontology.owl','steps':['Entities → Object properties → chọn contributionBy.','Hiện Domain=Contribution, Range=Person.','Giữ inverse hasContribution và ô Functional được chọn.'],'expect':'Đúng domain/range/inverse/functional của contributionBy. Nếu cần, chụp bổ sung hasRole hoặc director.'},
 'P06': {'file':'P06_filmmaker_equivalent_class.png','title':'Định nghĩa Filmmaker','owl':'Movie_Ontology.owl','steps':['Entities → Classes → chọn Filmmaker.','Mở Class Description → Equivalent To.','Hiện Person AND các nhánh SOME Directing/Writing/ProducingContribution.'],'expect':'Định nghĩa giao/hợp/tồn tại. Ảnh định nghĩa không tự chứng minh HermiT đã phân loại dữ liệu.'},
 'P07': {'file':'P07_filmstudio_cardinality.png','title':'Định nghĩa FilmStudio','owl':'Movie_Ontology.owl','steps':['Entities → Classes → chọn FilmStudio.','Mở Equivalent To; hiện min 3 productionOf Film.','Có thể chụp thêm MultiGenreFilm: min 2 hasGenre Genre.'],'expect':'Ảnh công thức cardinality. Kết quả 6 studio/30 phim nhiều thể loại của app dùng COUNT DISTINCT, không tự coi là chứng minh OWL DL.'},
 'P08': {'file':'P08_runtime_datatype.png','title':'Datatype của thời lượng','owl':'Movie_Ontology.owl','steps':['Entities → Data properties → chọn runtimeMinutes.','Hiện Domain=Film và Range=xsd:decimal.','Có thể chụp thêm releaseYear có range xsd:integer.'],'expect':'Thuộc tính dữ liệu nối thực thể với literal, khác quan hệ nối hai thực thể.'},
 'P09': {'file':'P09_inception_individual.png','title':'Cá thể Inception','owl':'Movie_Knowledge_Graph.owl','steps':['Mở ontology/Movie_Knowledge_Graph.owl.','Individuals → chọn film-Q25188 (Inception).','Hiện Film, title, releaseYear=2010, runtimeMinutes=148 và director.'],'expect':'Cá thể thật và thuộc tính khớp truy vấn. Giữ tên ontology để không chụp nhầm file chỉ có schema.'},
 'P10': {'file':'P10_nolan_asserted_types.png','title':'Kiểu khai báo của Nolan','owl':'Movie_Knowledge_Graph.owl','steps':['Mở Movie_Knowledge_Graph.owl, chọn person-Q25191 (Nolan).','Hiện Types trong chế độ asserted / trước suy luận.','Giữ dbo:Person và các quan hệ đóng góp/giải trong ảnh.'],'expect':'Kiểu gán gốc là Person; Filmmaker/AwardWinner trong app được bổ sung qua file phân loại. Nếu chụp sau reasoner, phải ghi rõ tên và trạng thái thực thi.'},
}

SLIDES=[]
def add(title,subtitle,kind,section,speech,**content):
    SLIDES.append({'number':len(SLIDES)+1,'title':title,'subtitle':subtitle,'kind':kind,'section':section,'speech':speech,**content})

add('MovieLOD','Ứng dụng dữ liệu phim liên kết · Semantic Web','cover','GIỚI THIỆU',
 'Chào thầy cô và các bạn. Nhóm chúng em trình bày MovieLOD, ứng dụng dữ liệu mở có liên kết về điện ảnh. Bài đi từ mô hình khái niệm, dữ liệu nguồn và RDF đến liên kết ngoài và truy vấn. Phiên bản hiện tại có 30 phim, 42 lớp ontology và 1.727 liên kết ngoài. Ví dụ xuyên suốt là Inception và Christopher Nolan. Bộ slide này có 24 trang; lời nói riêng và hướng dẫn chụp minh chứng Protégé đi kèm. Một số khung ảnh Protégé được để sẵn vì lần làm tài liệu này chưa chụp được giao diện trên máy. Các khung này ghi rõ yêu cầu, không được coi là ảnh minh chứng đã có.')

add('Bài giải quyết gì? Đối chiếu đủ 5 yêu cầu','Câu hỏi: ai làm gì trong phim nào, dữ liệu từ đâu và có thể truy vấn thế nào?','requirements','MỤC TIÊU',
 'Điện ảnh có nhiều thực thể và nhiều vai trò chồng lấp. Chúng ta muốn hỏi Nolan tham gia Inception ở những vai trò nào, phim này liên quan tới công ty nào hoặc dữ liệu lấy từ phản hồi nào. Năm yêu cầu của đề tạo thành một chuỗi công việc. Ontology định nghĩa khái niệm và quan hệ. Thu thập cung cấp dữ liệu thật. Chuyển đổi tạo RDF và IRI với giấy phép mở. Liên kết nối cá thể tới Wikidata và DBpedia. SPARQL cho phép đặt câu hỏi trên đồ thị. Đề còn yêu cầu báo cáo không quá 15 trang và video 3–5 phút; video demo hiện dài khoảng 4 phút 50 giây.',
 rows=[['YC1','Định nghĩa ontology','OWL/Turtle, lớp, quan hệ, restriction'],['YC2','Thu thập dữ liệu','API, phản hồi gốc, URL/time/hash'],['YC3','Chuyển thành mức 4 sao','RDF, HTTP IRI, giấy phép, công bố'],['YC4','Liên kết đạt mức 5 sao','sameAs, phương pháp nối, bản public'],['YC5','Giao diện SPARQL','Web, endpoint và terminal']])

add('Kiến trúc và đường đi của dữ liệu','Graph khai báo, schema và kết quả phân loại được lưu riêng','pipeline','KIẾN TRÚC',
 'Luồng xử lý bắt đầu từ danh sách phim trong config. collect lấy phản hồi nguồn và lưu metadata. build tạo ontology cùng graph RDF từ dữ liệu đã chuẩn hóa. validate kiểm tra trường ứng dụng, hash và truy vấn. reason bổ sung các kiểu phân loại ở file riêng. Web cục bộ gọi endpoint Flask dùng RDFLib; hosted dùng Comunica trong trình duyệt. Endpoint mặc định đọc movies.ttl, còn terminal với reasoned nạp thêm schema và inferred_classes.ttl. Tùy chọn này nạp kết quả phân loại đã lưu, không tự chạy reasoner mỗi lần truy vấn. Việc tách ba phần giúp phân biệt dữ kiện gốc với kiểu được bổ sung.',
 stages=[['01','THU THẬP','Wikidata / DBpedia\ncollect.py → data/raw/'],['02','TẠO RDF','build.py → movies.ttl\n+ ontology/movie.ttl'],['03','KIỂM TRA','validate.py / pytest\nnguồn, trường, truy vấn'],['04','PHÂN LOẠI','reason.py →\ninferred_classes.ttl']])

add('Bộ dữ liệu hiện tại: đọc đúng các con số','Mẫu 30 phim có chủ đích; số liệu lấy từ evidence/statistics.json','metrics','DỮ LIỆU',
 'Mẫu hiện có 30 phim, 851 người và 1.010 bản ghi đóng góp. Ngoài ra có 45 công ty, 672 thực thể giải thưởng, 75 thể loại, 11 quốc gia và 15 ngôn ngữ. 76 phản hồi gốc được giữ và kiểm tra hash. Dữ liệu gồm 19.339 triple, tách khỏi 518 triple lược đồ. Cần đọc đúng đơn vị: 672 là số thực thể giải khác nhau, không phải số lần trao giải; 1.010 là bản ghi một người giữ một vai trò trong một phim, không phải số người. Mọi phim trong mẫu có năm, thời lượng và đạo diễn, nhưng mẫu này không đại diện toàn bộ điện ảnh.',
 metrics=[['30','phim'],['851','người'],['1.010','đóng góp'],['45','công ty'],['672','thực thể giải'],['76/76','nguồn khớp hash']],
 footer='19.339 triple dữ liệu · 518 triple schema · 75 thể loại · 11 quốc gia · 15 ngôn ngữ')

add('YC1 · Ontology: 42 lớp, 6 nhóm khái niệm','Tái dùng trực tiếp dbo:Film, dbo:Person và dbo:Country','ontology_overview','YC1 · ONTOLOGY',
 'Ontology có 42 IRI lớp được khai báo owl Class, trong đó ba lớp dùng trực tiếp từ DBpedia, còn lại thuộc namespace của bài. Chúng ta có nhánh tác phẩm và phim; chủ thể người hoặc tổ chức; đóng góp và vai trò; thể loại; giải thưởng; và các lớp bổ trợ cho quốc gia, ngôn ngữ, nguồn, dataset. Trong số này, 14 lớp có kiểu được bổ sung từ định nghĩa hoặc quy tắc phân loại. Các lớp ngoài được tham chiếu qua equivalentClass có thể được Protégé tính thêm trong Metrics; vì vậy con số 42 dùng quy ước đếm lớp tự khai báo. Ảnh cần bổ sung ở bên phải là IRI ontology và versionInfo 2.0.0.',
 photo='P00',groups=[['11 lớp','CreativeWork / Film'],['8 lớp','Agent / Person / Organization'],['6 lớp','Contribution / ContributionRole'],['8 lớp','Genre'],['5 lớp','Award'],['4 lớp','Country / Language / SourceSnapshot / Dataset']])

add('YC1 · Cây lớp tác phẩm và phim','Lớp có tên và lớp được phân loại: phân biệt bằng ký hiệu (I)','hierarchy','YC1 · CÂY LỚP',
 'CreativeWork là nhánh tác phẩm. Film dùng IRI DBpedia và có các lớp con như FeatureFilm, AnimatedFilm, DocumentaryFilm. FeatureFilm và AnimatedFilm được ánh xạ theo quy tắc P31 của bài; đây là cách giản lược, không phải khẳng định đã kiểm tra mọi tiêu chí phát hành rạp. Các lớp ActionFilm, ComedyFilm, DramaFilm, ScienceFictionFilm, MultiGenreFilm và AwardWinningFilm được phân loại bổ sung. DocumentaryFilm hiện không có cá thể trong mẫu. Việc có một lớp trong mô hình không yêu cầu mẫu dữ liệu phải có sẵn mọi loại phim. Khung ảnh yêu cầu mở cây CreativeWork/Film và chọn Film để thấy IRI DBpedia.',
 photo='P01',tree=[(0,'CreativeWork'),(1,'dbo:Film'),(2,'FeatureFilm · 29 phim'),(2,'AnimatedFilm · 1 phim'),(2,'DocumentaryFilm · 0 phim'),(2,'ActionFilm (I)'),(2,'ComedyFilm (I)'),(2,'DramaFilm (I)'),(2,'ScienceFictionFilm (I)'),(2,'MultiGenreFilm (I)'),(2,'AwardWinningFilm (I)')],
 footer='(I): kiểu được bổ sung. FeatureFilm/AnimatedFilm theo ánh xạ P31; lớp tài liệu có 0 cá thể trong mẫu.')

add('YC1 · Người, tổ chức và vai trò nghề nghiệp','Một người có thể vừa là Actor vừa là Filmmaker','hierarchy','YC1 · CÂY LỚP',
 'Agent gồm Person và Organization. Person dùng lớp DBpedia và có các nhóm Actor, Filmmaker, AwardWinner. Organization có ProductionCompany; FilmStudio là nhóm công ty được ứng dụng phân loại theo ngưỡng số phim trong mẫu. Actor và Filmmaker không rời nhau, vì một người có thể vừa diễn xuất vừa đạo diễn hoặc biên kịch. Chúng ta cũng không dùng một lớp tổ hợp DirectorWriter để giữ hai nghề; từng công việc được ghi qua Contribution và SPARQL có thể JOIN các đóng góp. Số người hoặc công ty không được suy từ số dòng của một truy vấn có LIMIT. Ảnh cần chụp là cây Agent mở cả nhánh Person và Organization.',
 photo='P02',tree=[(0,'Agent'),(1,'dbo:Person · 851 người'),(2,'Actor (I) · 769'),(2,'Filmmaker (I) · 89'),(2,'AwardWinner (I) · 290'),(1,'Organization'),(2,'ProductionCompany · 45'),(3,'FilmStudio (I) · 6')],
 footer='Person / Organization là hai loại chủ thể. Actor và Filmmaker có thể chồng lấp vai trò.')

add('YC1 · Thể loại, giải thưởng và xuất xứ','Mỗi nhánh hỗ trợ một nhóm câu hỏi cụ thể','genre_award','YC1 · CÂY LỚP',
 'Genre có FictionGenre và NonFictionGenre; các lớp thể loại hành động, hài, chính kịch, khoa học viễn tưởng thuộc FictionGenre, còn DocumentaryGenre dưới NonFictionGenre. Award có các nhóm FilmAward, ActingAward, DirectingAward, WritingAward. Việc chia nhóm thể loại và giải hiện dùng từ khóa nhãn trong bước build, không phải suy luận tự khám phá nghĩa tiếng Anh. FilmAward là nhóm mặc định khi nhãn chưa khớp một nhóm nghề nghiệp. Các lớp Country, Language, SourceSnapshot và Dataset bổ sung bối cảnh và xuất xứ. Giải của người được giữ riêng với giải của phim. Khung ảnh cần mở hai nhánh Genre và Award, thu gọn nhánh khác để đọc rõ.',
 photo='P03',genre=['Genre','  FictionGenre','    ActionGenre','    ComedyGenre','    DramaGenre','    ScienceFictionGenre','  NonFictionGenre','    DocumentaryGenre'],awards=['Award','  FilmAward','  ActingAward','  DirectingAward','  WritingAward'],
 footer='Bổ trợ: dbo:Country · Language · SourceSnapshot · Dataset. Ánh xạ nhóm theo nhãn là quy tắc build.')

add('YC1 · Contribution: ai làm gì trong phim nào?','Một bản ghi nối đúng 1 người, 1 phim và 1 vai trò','contribution','YC1 · MÔ HÌNH',
 'Nếu chỉ gắn một nhãn nghề nghiệp cho Nolan, chúng ta không biết vai trò đó thuộc phim nào. Contribution giải quyết bằng một bản ghi nối một người, một phim và một vai trò. contributionBy trỏ Person, contributionTo trỏ Film, hasRole trỏ ContributionRole. Mỗi quan hệ có ràng buộc đúng một giá trị phù hợp. Bốn cá thể vai trò là DirectorRole, ActorRole, WriterRole, ProducerRole. Nolan giữ ba vai trò trong Inception, vì vậy có ba Contribution riêng. Các nhóm Acting, Directing, Writing, ProducingContribution được phân loại từ hasRole. Ảnh cần chụp Class Description của Contribution, hiện cả exactly 1 và các restriction về loại giá trị.',
 photo='P04',points=['4 vai trò: Director / Actor / Writer / Producer','Nolan trong Inception: Director + Writer + Producer','hasContribution / contributionOf là đường đi ngược','1.010 bản ghi; không ép mỗi người chỉ một nghề'])

add('YC1 · Quan hệ, domain/range và inverse','23 object property; chọn các quan hệ trung tâm để giải thích','properties','YC1 · THUỘC TÍNH',
 'Object property nối hai thực thể. contributionBy có domain Contribution và range Person; quan hệ ngược là hasContribution. contributionTo nối tới Film, hasRole nối tới ContributionRole. Ba quan hệ này có tính functional. Các quan hệ trực tiếp director, starring, writer, producer dùng từ DBpedia để hỏi thuận tiện. Những cặp như hasGenre/genreOf, hasProductionCompany/productionOf, hasAward/awardOf cho phép đi hai chiều. inverse là đảo hướng, không đồng nghĩa quan hệ đối xứng. Domain và range có thể giúp suy ra kiểu khi quan hệ được biết; chúng không tự đóng vai trò từ chối nhập liệu như một biểu mẫu. Ảnh yêu cầu chọn contributionBy để thấy domain/range/inverse/functional.',
 photo='P05',rows=[['contributionBy','Contribution → Person','hasContribution'],['contributionTo','Contribution → Film','contributionOf'],['hasRole','Contribution → Role','roleOf'],['dbo:director','Film → Person','directed'],['hasGenre','Film → Genre','genreOf'],['hasAward','Film hoặc Person → Award','awardOf']])

add('YC1 · OWL mô tả ngữ nghĩa như thế nào?','Các ràng buộc mô hình và kiểm tra trường ứng dụng có nhiệm vụ khác nhau','owl_rules','YC1 · NGỮ NGHĨA',
 'OWL cho phép định nghĩa tương đương lớp, giao, hợp, tồn tại, giá trị cố định và cardinality. Ví dụ Contribution có exactly một Person, một Film và một Role; DirectingContribution được nhận diện khi hasRole có giá trị DirectorRole. Quan hệ inverse suy ra đường đi ngược. Disjointness chỉ dùng cho các lớp không thể chồng lấp theo mô hình, không dùng cho Actor với Filmmaker. Cần nhớ giả định thế giới mở: thiếu một triple không tự chứng minh sự việc không có. Các IRI khác nhau cũng không tự bảo đảm là cá thể khác nhau. Vì vậy ứng dụng dùng kiểm tra Python riêng để phát hiện thiếu hoặc thừa trường, còn OWL phát biểu ý nghĩa và hỗ trợ phân loại.',
 cards=[['Định nghĩa lớp','equivalentClass + AND / OR / SOME\nVí dụ: Person có đóng góp làm phim → Filmmaker.'],['Cardinality và functional','Contribution: exactly 1 người / phim / vai trò.\nFunctional: nhiều nhất một giá trị theo OWL.'],['Inverse và disjointness','director ↔ directed; hasRole ↔ roleOf.\nActor và Filmmaker không disjoint.'],['Thế giới mở','Thiếu thông tin ≠ phủ định.\nPython kiểm tra trường bắt buộc; OWL không thay biểu mẫu.']])

add('YC1 · 14 lớp có kiểu được bổ sung','Graph gốc có 0 cá thể gán sẵn cho cả 14 lớp này','defined_table','YC1 · PHÂN LOẠI',
 'Bảng này cho thấy toàn bộ 14 lớp có kiểu được bổ sung. Bốn nhóm Contribution dùng role, ba nhóm người dùng đóng góp hoặc giải, năm nhóm phim dùng thể loại hoặc giải. Mười hai lớp thuộc phần xử lý bằng luật OWL RL. Hai lớp còn lại, MultiGenreFilm và FilmStudio, dùng truy vấn COUNT DISTINCT sau bước luật. Các số đếm chỉ tính tài nguyên nội bộ để tránh alias sameAs làm tăng số. Bảng là kết quả trong ontology_reasoning.json, không phải 14 kiểu gán sẵn trong movies.ttl. Hai truy vấn người có LIMIT 20; số hiển thị không phải tổng 769 Actor hoặc 89 Filmmaker. Phần cardinality được giải thích riêng ở slide sau.',
 footer='12 lớp: OWL RL, HermiT/Pellet khớp số lượng. 2 lớp cuối: COUNT DISTINCT; DL có 0 cá thể.')

add('YC1 · Ví dụ suy luận: Christopher Nolan','Contribution với DirectorRole → DirectingContribution → Filmmaker','nolan_chain','YC1 · SUY LUẬN',
 'Dữ liệu gốc chỉ khai báo Nolan là Person, cùng các quan hệ đóng góp và giải. Một Contribution của Nolan trong Inception có DirectorRole. Định nghĩa hasValue phân loại bản ghi này là DirectingContribution. Từ Person có loại đóng góp đạo diễn, biên kịch hoặc sản xuất, định nghĩa dùng giao, hợp và tồn tại phân loại Nolan là Filmmaker. Nolan còn có giải riêng nên được bổ sung AwardWinner. Đây là khác biệt giữa kiểu gán ban đầu và kiểu suy ra trong ứng dụng. Khung ảnh yêu cầu Class Description và Equivalent To của Filmmaker. Ảnh này chứng minh công thức đã khai báo; kết quả thực thi được kiểm chứng riêng bằng terminal và tests.',
 photo='P06',steps=[['DỮ KIỆN','Nolan a dbo:Person\nc hasRole DirectorRole'],['LUẬT 1 · hasValue','c a DirectingContribution'],['LUẬT 2 · SOME + OR','Nolan a Filmmaker']],
 footer='Nolan: Person (gốc) → Person + Filmmaker + AwardWinner (khi nạp file phân loại).')

add('YC1 · Cardinality: ngưỡng 2 và ngưỡng 3','Định nghĩa OWL và cách ứng dụng đếm IRI phải được phân biệt','cardinality','YC1 · GIỚI HẠN LUẬT',
 'MultiGenreFilm được định nghĩa là Film có ít nhất hai Genre; FilmStudio là ProductionCompany có ít nhất ba Film qua productionOf. Trong mẫu, toàn bộ 30 phim có ít nhất hai thể loại và có sáu công ty đạt ngưỡng ba phim. Warner Bros. liên quan tới 11 phim trong mẫu. owlrl không xử lý các ngưỡng này theo nhu cầu của bài, nên reason.py dùng COUNT DISTINCT bổ sung sau khi suy ra inverse. Đếm IRI khác nhau là quy tắc ứng dụng; trong OWL, hai tên khác nhau có thể chỉ cùng một cá thể. HermiT/Pellet đã chạy: hai lớp này có không cá thể được suy luận, còn 30 và sáu là số đếm trong ứng dụng. Ảnh cần chụp công thức min 3 của FilmStudio, không yêu cầu giả lập kết quả reasoner.',
 photo='P07',cards=[['MultiGenreFilm','Film + min 2 hasGenre.Genre\nKết quả ứng dụng: 30/30 phim.'],['FilmStudio','ProductionCompany + min 3 productionOf.Film\n6 công ty; Warner Bros.: 11 phim.']],
 footer='FILTER namespace nội bộ + COUNT(DISTINCT IRI): tránh đếm các alias sameAs thành nhiều cá thể.')

add('YC2 · Thu thập thật và giữ xuất xứ','76/76 phản hồi gốc có, 76/76 SHA-256 khớp','collection','YC2 · NGUỒN',
 'Danh tính phim được xác định qua sitelink Wikipedia tiếng Anh chính xác, thay vì so tên gần giống. Wikidata cung cấp đạo diễn P57, diễn viên P161, biên kịch P58, nhà sản xuất P162, giải P166 và công ty P272. DBpedia chỉ nối khi chủ thể khớp tiêu đề và có kiểu Film; vì vậy có 28 liên kết DBpedia thay vì tự đoán đủ 30. Mỗi phản hồi có URL, provider, thời điểm, HTTP status, SHA-256 và đường dẫn. Hiện đủ 76 phản hồi và hash khớp. Một phản hồi tải lại đổi nội dung được ghi hash/time mới, đồng thời giữ danh mục lịch sử. Hash kiểm tra toàn vẹn byte, không chứng minh mọi phát biểu ngoài đời đúng.',
 image='evidence/demo/03_sources.png',cards=[['Xác định đúng thực thể','Wikidata: sitelink Wikipedia chính xác.\nDBpedia: root phải được khai báo Film.'],['Thuộc tính thu thập','P57 / P161 / P58 / P162: người và vai trò.\nP166: giải; P272: công ty; còn năm/thời lượng/thể loại.'],['Truy nguồn và tái lập','URL + thời điểm + HTTP status + SHA-256.\ncollect từ cache → build → validate đã chạy lại.']])

add('YC3 · RDF và giá trị có datatype','19.339 triple dữ liệu · 518 triple schema · Turtle / JSON-LD / OWL','rdf','YC3 · CHUYỂN ĐỔI',
 'Một triple gồm chủ thể, quan hệ và đối tượng hoặc giá trị. Inception có đạo diễn Nolan, năm 2010 và thời lượng 148 phút. Quan hệ đạo diễn nối hai thực thể; năm và thời lượng là literal có datatype. Dùng QID để tạo IRI ổn định; chuẩn hóa các đơn vị giờ, phút, giây về phút và ghi các trường hợp nguồn có nhiều giá trị. Sáu datatype property khai báo là title, releaseYear, runtimeMinutes, sourceUrl, retrievedAt, sha256. Turtle và JSON-LD biểu diễn cùng graph; file OWL riêng có schema, file Knowledge Graph có schema và dữ liệu. Ảnh cần chọn runtimeMinutes trong Data properties để thấy domain Film và range decimal.',
 photo='P08',code='res:film-Q25188 a dbo:Film ;\n  ex:title "Inception" ;\n  ex:releaseYear 2010 ;\n  ex:runtimeMinutes "148.0"^^xsd:decimal ;\n  dbo:director res:person-Q25191 .',
 rows=[['title','string'],['releaseYear','integer'],['runtimeMinutes','decimal'],['sourceUrl','anyURI'],['retrievedAt','dateTime'],['sha256','string']])

add('YC3–YC4 · Từ RDF đến Linked Open Data','Mức sao cộng dồn; công bố và liên kết được kiểm chứng trên bản hiện tại','lod','YC3 / YC4 · CÔNG BỐ',
 'Mức một sao bắt đầu với dữ liệu trên Web có giấy phép mở; hai sao là có cấu trúc; ba sao dùng định dạng mở; bốn sao dùng HTTP URI và chuẩn RDF để tra cứu; năm sao thêm liên kết tới dữ liệu khác. Bài có giấy phép CC BY-SA 4.0, RDF/Turtle/JSON-LD và các IRI có trang mô tả. Bản công khai đã được kiểm tra không đăng nhập, cả bốn graph RDF đối chiếu đều đẳng cấu với local. Có 1.699 liên kết Wikidata và 28 DBpedia. sameAs khẳng định cùng danh tính, còn sourceSnapshot ghi xuất xứ. Tái dùng dbo:Film là dùng từ vựng lớp ở YC1, khác liên kết cá thể ở YC4.',
 stars=[['1 sao','Public + giấy phép mở','CC BY-SA 4.0'],['2 sao','Dữ liệu có cấu trúc','Phim, người, vai trò, thuộc tính'],['3 sao','Định dạng mở','CSV / Turtle / JSON-LD'],['4 sao','HTTP IRI + RDF + tra cứu','Mô tả HTML, JSON-LD và RDF'],['5 sao','Liên kết dataset khác','1.699 Wikidata + 28 DBpedia']],
 footer='sameAs: cùng một thực thể. sourceSnapshot: xuất xứ. 4 graph public kiểm tra đều khớp local.')

add('YC3 · Tra cứu IRI của Inception','Một định danh có mô tả cho người đọc và dữ liệu máy có thể đọc','resource','YC3 · MINH CHỨNG',
 'Trang Inception hiển thị tên, kiểu, năm, thời lượng, đạo diễn, đóng góp, liên kết ngoài và nguồn. Người đọc có thể tải mô tả Turtle; HTML cũng nhúng JSON-LD. Ở Flask local, Accept text turtle trả 303 đến mô tả RDF và curl trừ L theo chuyển hướng. Hosted tĩnh cung cấp HTML/JSON-LD và link RDF; không tự khẳng định nó có cùng hành vi 303 như Flask. Bên trái là ảnh ứng dụng thật. Bên phải là khung cần ảnh Individuals trong Protégé khi mở Knowledge Graph: chọn film-Q25188 và hiện kiểu cùng các thuộc tính. Không mở file chỉ schema để chụp cá thể.',
 photo='P09',image='evidence/screenshots/09_inception_resource.png',
 footer='Ảnh trái: ứng dụng thật. Ảnh phải: cần chụp Individuals của Inception trong Movie_Knowledge_Graph.owl.')

add('YC5 · Truy vấn Inception trên Web','SELECT → bảng gồm title, year, runtimeMinutes và director','query','YC5 · WEB',
 'Truy vấn đầu tiên tìm phim tên Inception, đi theo director tới người và lấy nhãn người đó. Kết quả là Inception, 2010, 148 phút, Christopher Nolan. SELECT chọn cột, WHERE đưa mẫu đồ thị, dấu hỏi đánh dấu biến. OPTIONAL giữ dòng khi thuộc tính năm hoặc thời lượng có thể thiếu. Người dùng có thể sửa truy vấn, bấm Run query và tải kết quả. Giao diện có 14 mẫu trực tiếp. Ngoài SELECT trả bảng, ASK trả True hoặc False, CONSTRUCT tạo graph RDF. Kết quả được tính từ graph; danh sách phim hoặc tên đạo diễn không được nhập cứng trong bảng.',
 image='evidence/screenshots/05_inception_current.png',code='SELECT ?title ?year ?runtimeMinutes ?director\nWHERE {\n  ?film a dbo:Film ; ex:title "Inception" ;\n        ex:title ?title ; dbo:director ?person .\n  ?person rdfs:label ?director .\n  OPTIONAL { ?film ex:releaseYear ?year }\n  OPTIONAL { ?film ex:runtimeMinutes ?runtimeMinutes }\n}',
 footer='Dùng PREFIX của queries/02_inception.rq. Kết quả thật: 2010 · 148 phút · Christopher Nolan.')

add('YC5 · Một người, nhiều vai trò và nhiều câu hỏi','Ảnh đã lọc riêng Nolan: Director, Writer và Producer trong Inception','roles','YC5 · ỨNG DỤNG',
 'Câu hỏi toàn bộ đóng góp Inception trả 25 bản ghi, gồm 21 diễn viên, một đạo diễn, một biên kịch và hai nhà sản xuất. Ảnh trên slide lọc riêng Christopher Nolan nên chỉ còn ba dòng: Director, Writer, Producer. Chúng ta không lấy ba dòng này làm tổng đóng góp. Các truy vấn khác cho biết tám phim do Nolan đạo diễn trong mẫu, bốn công ty liên quan Inception và bảy giải của The Godfather. Việc thêm câu hỏi không cần nhập một bảng kết quả riêng; chúng dùng cùng đồ thị và mô hình. Download results xuất kết quả đang hiển thị. Các file truy vấn và biên bản cho phép kiểm tra lại những số này.',
 image='evidence/screenshots/06_nolan_roles.png',cards=[['25 bản ghi','Đóng góp Inception; 3 dòng trong ảnh chỉ là Nolan.'],['8 / 4 / 7','8 phim Nolan · 4 công ty Inception · 7 giải Godfather.'],['14 mẫu Web / 24 file','Trực tiếp; hierarchy cần schema; phân loại cần --reasoned.']])

add('YC5 · Endpoint, terminal và kiểu được bổ sung','Cùng câu hỏi Nolan: 1 kiểu gốc → 3 kiểu khi nạp kết quả phân loại','endpoint','YC5 · KIỂM CHỨNG',
 'Bài có endpoint GET/POST và terminal, ngoài giao diện Web. SELECT và ASK trả JSON; CONSTRUCT và DESCRIBE trả Turtle. Endpoint mặc định chỉ nạp graph khai báo. Lệnh query.py với reasoned nạp thêm schema và inferred_classes.ttl. Cùng câu 24 trên Nolan trả một kiểu Person khi chạy gốc; chạy reasoned trả Person, Filmmaker, AwardWinner. File kiểu được tạo trước bởi reason.py, không tính suy luận mỗi lần gọi query.py. Truy vấn hierarchy như câu 13 cần schema; Actor/Filmmaker có LIMIT 20 nên tổng thực ở biên bản là 769 và 89. Khung ảnh Protégé yêu cầu Types của Nolan ở chế độ asserted; nếu ảnh sau reasoner phải ghi rõ trạng thái.',
 photo='P10',code='curl -X POST http://127.0.0.1:8000/sparql \\\n  -H "Content-Type: application/sparql-query" \\\n  --data-binary @queries/02_inception.rq\n\n.venv/bin/python src/query.py \\\n  queries/24_nolan_asserted_types_only.rq\n.venv/bin/python src/query.py \\\n  queries/24_nolan_asserted_types_only.rq --reasoned',
 rows=[['Graph gốc','dbo:Person'],['Có phân loại','Person + Filmmaker + AwardWinner']])

add('Kiểm tra dữ liệu, ứng dụng và bản công khai','Minh chứng thực thi nằm ở evidence/, không chỉ là mô tả trong báo cáo','validation','KIỂM TRA',
 'validate đã kiểm tra tên, nguồn, liên kết của phim và các thành phần Contribution; 76 hash nguồn khớp và 24 file truy vấn đã chạy ở chế độ dữ liệu phù hợp. Có 14 test pass và chín kiểm tra trình duyệt đạt, gồm endpoint, Comunica, lỗi cú pháp, ASK, CONSTRUCT, trang IRI và màn hình mobile. Bản công khai được kiểm tra qua tám URL không có cookie hay đăng nhập; bốn graph RDF đều đẳng cấu với local, có giấy phép và link mô tả máy đọc được. HermiT/Pellet riêng đã xác nhận OWL nhất quán và không có lớp không khả thỏa. Test và hash không chứng minh mọi thông tin ngoài đời đúng. Timestamp OWL/Turtle/JSON-LD đã đồng bộ đến mili giây. Đó là lý do cần vừa nêu kết quả vừa giữ giới hạn phương pháp.',
 image='evidence/screenshots/11_validation_current.png',checks=[['76/76','Nguồn khớp hash'],['24','File truy vấn đã chạy'],['14 + 9','Test + browser checks'],['8 URL / 4 graph','Public 200 / đẳng cấu local']])

add('Đối chiếu đề và giới hạn cần nói rõ','5/5 yêu cầu có minh chứng; 10/10 là điểm tự đề xuất','score_limits','ĐÁNH GIÁ',
 'Ảnh đề gốc không đưa trọng số; nhóm dùng thang tự đánh giá chia đều hai điểm mỗi yêu cầu. Ontology, thu thập, RDF công khai, liên kết và truy vấn đều có minh chứng đạt nên đề xuất mười trên mười. Đây không phải điểm chính thức của giảng viên. Các giới hạn vẫn còn: mẫu 30 phim có chủ đích; nhóm thể loại và giải ánh xạ theo nhãn; chưa có ngân sách hoặc streaming; HermiT/Pellet đã xác nhận nhất quán, còn hai nhóm cardinality chỉ có số đếm ứng dụng 30/6; DL có không cá thể. SQL cũng có thể trả nhiều câu hỏi bằng JOIN/view/quy tắc. Giá trị Semantic Web ở đây là IRI dùng chung, từ vựng tái dùng, liên kết dataset, xuất xứ và định nghĩa ngữ nghĩa tường minh.',
 rows=[['YC1','Ontology + OWL + test','2/2'],['YC2','76 nguồn + hash + tái lập','2/2'],['YC3','RDF public khớp local','2/2'],['YC4','1.727 liên kết đã công bố','2/2'],['YC5','Web / endpoint / terminal','2/2']],
 cards=[['Giới hạn dữ liệu','30 phim có chủ đích; nhóm theo nhãn.\nHash ≠ sự thật ngoài đời; chưa có ngân sách/streaming.'],['Giới hạn reasoning','12 lớp OWL RL; 2 lớp đếm IRI.\nHermiT/Pellet: nhất quán; DL hai lớp ngưỡng = 0.'],['Giá trị Semantic Web','IRI + từ vựng chung + liên kết + xuất xứ.\nKhông nói SQL không thể trả các câu hỏi này.']])

add('Kết luận và ảnh Protégé cần bổ sung','24 slide · báo cáo 5 trang · video demo 4 phút 50 giây','closing','HOÀN THIỆN',
 'MovieLOD đã nối mô hình, dữ liệu thật, nguồn, RDF, liên kết và truy vấn trong một ứng dụng. Bản này có 24 slide; nhóm có thể trình bày đầy đủ khoảng 18–22 phút hoặc chọn các trang chính để rút gọn. Trước khi nộp, điền tên thành viên và bổ sung các ảnh Protégé theo mã trên bảng. Các khung ảnh và hướng dẫn đã có ngay ở những slide liên quan. Giao diện macOS chưa cho phép chụp trong lần làm tài liệu này, nên không có ảnh Protégé giả được gắn vào. Có thể chèn ảnh trực tiếp trong PowerPoint hoặc lưu đúng tên ở evidence/protege rồi chạy lại trình tạo slide. Nhóm xin kết thúc và sẵn sàng trả lời câu hỏi.',
 footer='Tất cả khung ảnh là chỗ chờ bổ sung, không phải minh chứng đã chụp. Lời nói đầy đủ nằm trong Speaker Notes.')

assert len(SLIDES)==24
