"""English slide content; retain Vietnamese screenshot guidance and rehearsal text."""
from copy import deepcopy
from presentation_content import SLIDES as VI_SLIDES, PROTEGE_SHOTS as VI_SHOTS

SLIDES = deepcopy(VI_SLIDES)
PROTEGE_SHOTS = deepcopy(VI_SHOTS)
PHOTO_TITLES = ['Ontology IRI and version', 'Film class hierarchy', 'People and organizations',
                'Genre and award hierarchies', 'Contribution restrictions',
                'Domain, range, inverse and functional', 'Filmmaker definition',
                'FilmStudio cardinality', 'Runtime datatype', 'Inception individual',
                'Nolan asserted types']
for key, title in zip(PROTEGE_SHOTS, PHOTO_TITLES):
    PROTEGE_SHOTS[key]['title_en'] = title
for slide in SLIDES:
    slide['speech_vi'] = slide['speech']

def update(number, title, subtitle, speech, **content):
    SLIDES[number-1].update(title=title, subtitle=subtitle, speech=speech, section=title.split(' · ')[0], **content)

update(1, 'MovieLOD', 'Linked movie data application · Semantic Web',
       'Welcome. We present MovieLOD, a linked open data application for movies. The project connects a domain ontology, real source responses, RDF, external links and SPARQL queries. The current version contains 30 films, 42 declared classes and 1,727 external identity links. Inception and Christopher Nolan are our running examples. This deck has 24 slides. Vietnamese instructions remain inside the 11 empty Protégé screenshot slots so the team can add genuine evidence. These slots are placeholders, not screenshots. The demo video remains unchanged.')
update(2, 'Problem and five assignment requirements',
       'Who did what in which film? Where did the data come from? How can we query it?',
       'Movie data contains many related entities and overlapping roles. We want to identify Nolan’s roles in Inception, its production companies and the source of each claim. The five requirements form a workflow: define an ontology, collect real data, publish RDF with HTTP identifiers and an open license, link entities to external datasets, and provide SPARQL interfaces. Deliverables include a report of at most 15 pages, slides and a three-to-five-minute demo. The current video runs for about four minutes and fifty seconds.',
       rows=[['R1','Define an ontology','OWL/Turtle, classes, properties and restrictions'],['R2','Collect domain data','APIs, raw responses, URLs, timestamps and hashes'],['R3','Publish four-star data','RDF, HTTP IRIs, open license and publication'],['R4','Link to reach five stars','sameAs links, matching method and public data'],['R5','Provide SPARQL interfaces','Web application, endpoint and terminal']])
update(3, 'Architecture and data flow', 'Asserted data, schema and inferred types are stored separately',
       'The pipeline starts with the film list in config. collect.py fetches responses and stores provenance metadata. build.py creates the ontology and normalized RDF graph. validate.py checks application fields, source hashes and queries. reason.py writes additional types to a separate file. The local application uses Flask and RDFLib; the hosted application runs Comunica in the browser. The endpoint loads movies.ttl by default. The terminal --reasoned option also loads the schema and saved inferred types; it does not start a reasoner for every query. All RDF exports now use millisecond timestamps, while raw source metadata retains its original precision.',
       stages=[['01','COLLECT','Wikidata / DBpedia\ncollect.py → data/raw/'],['02','BUILD RDF','build.py → movies.ttl\n+ ontology/movie.ttl'],['03','VALIDATE','validate.py / pytest\nsources, fields and queries'],['04','CLASSIFY','reason.py →\ninferred_classes.ttl']])
update(4, 'Current dataset: interpreting the numbers', 'A selected sample of 30 films · evidence/statistics.json',
       'The sample contains 30 films, 851 people and 1,010 contribution records. It also includes 45 companies, 672 award entities, 75 genres, 11 countries and 15 languages. All 76 raw source responses are present and their hashes match. The asserted graph has 19,339 triples, separate from 518 schema triples. Units matter: 672 counts distinct award entities, not award events; 1,010 counts person-film-role records, not people. All sampled films have a year, runtime and director. This selected sample does not represent the entire film industry.',
       metrics=[['30','films'],['851','people'],['1,010','contributions'],['45','companies'],['672','award entities'],['76/76','verified source hashes']],
       footer='19,339 data triples · 518 schema triples · 75 genres · 11 countries · 15 languages')
update(5, 'R1 · Ontology: 42 classes in six groups', 'Direct reuse of dbo:Film, dbo:Person and dbo:Country',
       'The ontology declares 42 named owl:Class IRIs. Three directly reuse DBpedia classes; the other 39 belong to our namespace. The six groups cover creative works and films, people and organizations, contributions and roles, genres, awards, and supporting context and provenance. Fourteen classes receive additional types through definitions or application rules. Protégé Metrics may include referenced external classes, so its total can differ from our count of explicitly declared classes. The screenshot slot requests the ontology IRI and versionInfo 2.0.0.',
       groups=[['11 classes','CreativeWork / Film'],['8 classes','Agent / Person / Organization'],['6 classes','Contribution / ContributionRole'],['8 classes','Genre'],['5 classes','Award'],['4 classes','Country / Language / SourceSnapshot / Dataset']])
update(6, 'R1 · Creative works and film classes', 'Class definitions and additional instance types · (I) marks additional classification',
       'CreativeWork is the top-level branch for works. Film reuses the DBpedia IRI. Its subclasses include FeatureFilm, AnimatedFilm and DocumentaryFilm. FeatureFilm and AnimatedFilm follow the project’s P31 mapping, a simplified rule rather than a full release-policy assessment. Genre-based film classes and AwardWinningFilm receive inferred types. MultiGenreFilm receives types through a separate counting rule in the application. DocumentaryFilm has no instances in this sample; defining a class does not require a sample instance. The requested Protégé view shows the asserted CreativeWork/Film hierarchy and Film’s DBpedia IRI.',
       tree=[(0,'CreativeWork'),(1,'dbo:Film'),(2,'FeatureFilm · 29 films'),(2,'AnimatedFilm · 1 film'),(2,'DocumentaryFilm · 0 films'),(2,'ActionFilm (I)'),(2,'ComedyFilm (I)'),(2,'DramaFilm (I)'),(2,'ScienceFictionFilm (I)'),(2,'MultiGenreFilm (I)'),(2,'AwardWinningFilm (I)')],
       footer='(I): additional types. FeatureFilm/AnimatedFilm follow P31 mapping; DocumentaryFilm has no sample instances.')
update(7, 'R1 · People, organizations and roles', 'A person may be both an Actor and a Filmmaker',
       'Agent includes Person and Organization. Person reuses DBpedia and has Actor, Filmmaker and AwardWinner subclasses. Organization includes ProductionCompany. The application classifies six companies as FilmStudio using the number of film IRIs, while the DL reasoners infer no FilmStudio instances under the current axioms. Actor and Filmmaker are not disjoint: a person can act and also direct or write. Each role is represented by its own Contribution, rather than a combined DirectorWriter class. A query with LIMIT cannot establish the total number of people. The screenshot slot requests both Person and Organization branches.',
       tree=[(0,'Agent'),(1,'dbo:Person · 851 people'),(2,'Actor (I) · 769'),(2,'Filmmaker (I) · 89'),(2,'AwardWinner (I) · 290'),(1,'Organization'),(2,'ProductionCompany · 45'),(3,'FilmStudio · 6 by counting; DL: 0')],
       footer='Person and Organization are different kinds of agent. Actor and Filmmaker may overlap.')
update(8, 'R1 · Genres, awards and provenance', 'Each branch supports a specific group of questions',
       'Genre contains FictionGenre and NonFictionGenre. Action, comedy, drama and science fiction genres belong to FictionGenre; DocumentaryGenre belongs to NonFictionGenre. Award includes FilmAward, ActingAward, DirectingAward and WritingAward. These groups are mapped from label keywords during build, rather than discovered automatically by reasoning. FilmAward is the fallback group when no role-specific keyword matches. Country, Language, SourceSnapshot and Dataset supply context and provenance. Awards received by people are kept distinct from awards received by films. The requested view shows the Genre and Award branches.',
       footer='Supporting classes: dbo:Country · Language · SourceSnapshot · Dataset. Group mapping uses label keywords.')
update(9, 'R1 · Contribution: who did what in a film?', 'One record connects exactly one person, one film and one role',
       'A profession label alone does not identify a person’s role in a particular film. Contribution connects a person, film and role. contributionBy points to Person, contributionTo to Film, and hasRole to ContributionRole. Each relation has an exactly-one qualified restriction. Four role individuals are DirectorRole, ActorRole, WriterRole and ProducerRole. Nolan has three roles in Inception, represented by three separate contributions. Acting, Directing, Writing and ProducingContribution are classified from hasRole. The screenshot should show Contribution’s restrictions, including exactly-one and allValuesFrom expressions.',
       points=['Four roles: Director / Actor / Writer / Producer','Nolan in Inception: Director + Writer + Producer','hasContribution / contributionOf provide inverse paths','1,010 records; people may hold multiple roles'])
update(10, 'R1 · Properties, domain/range and inverses', '23 object properties · selected central relationships',
       'An object property connects two entities. contributionBy has domain Contribution, range Person and inverse hasContribution. contributionTo connects to Film; hasRole connects to ContributionRole. These three properties are functional. Direct director, starring, writer and producer properties reuse DBpedia vocabulary. Inverse pairs such as hasGenre/genreOf and hasAward/awardOf support navigation in either direction. An inverse is not a symmetric property. Domain and range can infer types; they are not input-rejection rules. The requested screenshot shows contributionBy’s domain, range, inverse and functional characteristic.',
       rows=[['contributionBy','Contribution → Person','hasContribution'],['contributionTo','Contribution → Film','contributionOf'],['hasRole','Contribution → Role','roleOf'],['dbo:director','Film → Person','directed'],['hasGenre','Film → Genre','genreOf'],['hasAward','Film or Person → Award','awardOf']])
update(11, 'R1 · How OWL expresses meaning', 'Ontology constraints and application validation serve different purposes',
       'OWL supports equivalent class definitions, intersections, unions, existential restrictions, fixed values and cardinality. Contribution connects exactly one suitable Person, Film and Role. A contribution with DirectorRole belongs to DirectingContribution. Inverse properties support reverse paths. Disjointness is used for incompatible entity categories, not for Actor and Filmmaker. Under the open-world assumption, a missing triple is not evidence that something is false. Different IRIs need not denote different individuals. Python checks required application fields, while OWL expresses meaning and supports classification.',
       cards=[['Class definitions','equivalentClass + AND / OR / SOME\nA Person with filmmaking contributions → Filmmaker.'],['Cardinality and functional','Contribution: exactly one person / film / role.\nFunctional: at most one value under OWL semantics.'],['Inverse and disjointness','director ↔ directed; hasRole ↔ roleOf.\nActor and Filmmaker are not disjoint.'],['Open-world assumption','Missing information ≠ negation.\nPython validates required fields; OWL defines meaning.']])
update(12, 'R1 · Fourteen classes with additional types', 'None of these 14 types is asserted in the original data graph',
       'This table summarizes additional classification in the application. Four contribution classes use roles, three person classes use contributions or awards, and five film classes use genres or awards. Those twelve classes use OWL RL, and their counts are independently confirmed by HermiT and Pellet. MultiGenreFilm and FilmStudio use COUNT DISTINCT after rule closure. Counts include only local resource IRIs to avoid duplicate sameAs aliases. This application table comes from ontology_reasoning.json. HermiT and Pellet infer zero instances for the two counting classes. Person queries have LIMIT 20, so their returned rows are not the totals of 769 Actors or 89 Filmmakers.',
       footer='12 classes: OWL RL, with matching HermiT/Pellet counts. Last 2: COUNT DISTINCT; DL instances: 0.')
update(13, 'R1 · Inference example: Christopher Nolan', 'DirectorRole → DirectingContribution → Filmmaker',
       'The asserted data types Nolan as Person and records his contributions and awards. One of his Inception contributions has DirectorRole. A hasValue definition classifies it as DirectingContribution. Filmmaker combines Person with the existence of a directing, writing or producing contribution. Nolan also receives awards, so he is inferred to be an AwardWinner. HermiT and Pellet confirm both types. The screenshot slot requests Filmmaker’s Equivalent To expression. A definition screenshot proves the axiom is present; execution logs separately demonstrate the inference.',
       steps=[['FACTS','Nolan a dbo:Person\nc hasRole DirectorRole'],['RULE 1 · hasValue','c a DirectingContribution'],['RULE 2 · SOME + OR','Nolan a Filmmaker']],
       footer='Nolan: Person (asserted) → Person + Filmmaker + AwardWinner (with inferred types).')
update(14, 'R1 · Cardinality: thresholds of two and three', 'Distinguish OWL definitions from counting distinct RDF terms',
       'MultiGenreFilm is a Film with at least two Genres. FilmStudio is a ProductionCompany with at least three Films through productionOf. All 30 sampled films have at least two genre IRIs; six companies meet the application’s three-film threshold. Warner Bros. is linked to eleven sampled films. reason.py uses COUNT DISTINCT after inverse-property closure because OWL RL does not cover these thresholds. Different IRIs need not be different individuals under OWL semantics. HermiT and Pellet infer zero instances for both classes. The figures thirty and six are application counts, not DL membership results. Capture the actual class definitions in Protégé.',
       cards=[['MultiGenreFilm','Film + min 2 hasGenre.Genre\nApplication: 30/30 films; DL: 0 inferred.'],['FilmStudio','ProductionCompany + min 3 productionOf.Film\nApplication: 6 companies; DL: 0 inferred.']],
       footer='Local namespace filter + COUNT(DISTINCT IRI) avoids counting sameAs aliases as separate values.')
update(15, 'R2 · Real collection and traceable sources', '76/76 raw responses present · 76/76 SHA-256 hashes match',
       'Film identity is resolved through an exact English Wikipedia sitelink, rather than approximate title matching. Wikidata supplies directors, actors, writers, producers, awards and production companies. DBpedia links require the matched root subject to be a Film, resulting in twenty-eight verified links rather than guessing thirty. Each saved response has a URL, provider, timestamp, HTTP status, SHA-256 and path. All 76 responses are present and verified. A re-fetched response that changed was assigned its new timestamp and hash while retaining the historical manifest. Hashes verify byte integrity, not the truth of every claim.',
       image='evidence/screenshots/12_sources_en.png',
       cards=[['Resolve the right entity','Wikidata: exact Wikipedia sitelink.\nDBpedia: matched root must be typed Film.'],['Collect relevant claims','P57 / P161 / P58 / P162: people and roles.\nP166: awards; P272: companies; year/runtime/genre.'],['Trace and reproduce','URL + retrieval time + HTTP status + SHA-256.\nCached collect → build → validate rerun.']])
update(16, 'R3 · RDF and typed literal values', '19,339 data triples · 518 schema triples · Turtle / JSON-LD / OWL',
       'An RDF triple has a subject, predicate and object or literal. Inception is directed by Nolan, released in 2010 and has a runtime of 148 minutes. director links entities; year and runtime are typed literals. QIDs produce stable local IRIs. Hours, minutes and seconds are normalized to minutes, with ambiguous source values recorded for review. The six declared data properties are title, releaseYear, runtimeMinutes, sourceUrl, retrievedAt and sha256. All exports use millisecond timestamps. Turtle and JSON-LD represent the same graph; the main Knowledge Graph OWL contains schema and data. The screenshot slot requests runtimeMinutes with Film domain and decimal range.')
update(17, 'R3–R4 · From RDF to Linked Open Data', 'Star levels are cumulative · publication and links are verified',
       'One-star data is available on the Web with an open license. Two-star data is structured; three-star data uses open formats. Four-star data uses HTTP identifiers and RDF for lookup. Five-star data adds links to other datasets. The project publishes CC BY-SA 4.0 data in Turtle and JSON-LD with resolvable descriptions. Four public RDF graphs were compared with local graphs without authentication. There are 1,699 Wikidata and 28 DBpedia identity links. sameAs expresses shared identity; sourceSnapshot records provenance. Reusing dbo:Film is vocabulary reuse in R1, distinct from linking individuals in R4.',
       stars=[['1 star','Public data + open license','CC BY-SA 4.0'],['2 stars','Structured data','Films, people, roles and attributes'],['3 stars','Open formats','CSV / Turtle / JSON-LD'],['4 stars','HTTP IRIs + RDF + lookup','HTML, JSON-LD and RDF descriptions'],['5 stars','Links to external datasets','1,699 Wikidata + 28 DBpedia']],
       footer='sameAs: shared identity. sourceSnapshot: provenance. All four checked public RDF graphs match local data.')
update(18, 'R3 · Looking up Inception’s IRI', 'One identifier offers readable and machine-readable descriptions',
       'The Inception page shows its title, types, year, runtime, director, contributions, external links and provenance. Readers can download Turtle; HTML also embeds JSON-LD. The local Flask server responds to a Turtle Accept header with a 303 redirect, which curl -L follows. The static hosted site provides HTML, JSON-LD and an RDF link; we do not claim it reproduces Flask’s 303 behavior. The left image is a real application screenshot. The right slot requests the Inception individual from the full Knowledge Graph in Protégé. A schema-only file has no film individuals to capture.',
       footer='Left: real application screenshot. Right: pending Protégé evidence for Inception in the main Knowledge Graph.')
update(19, 'R5 · Querying Inception on the Web', 'SELECT → title, year, runtimeMinutes and director',
       'The first query matches Inception, follows director to a person and retrieves the person’s label. It returns Inception, 2010, 148 minutes and Christopher Nolan. SELECT chooses columns, WHERE matches graph patterns and question marks denote variables. OPTIONAL preserves rows when year or runtime is absent. Users can edit the query, run it and export results. The interface offers fourteen direct samples. ASK returns a boolean; CONSTRUCT returns an RDF graph. The query engine computes the results from RDF rather than displaying a hard-coded result table.',
       footer='Use the PREFIX declarations in queries/02_inception.rq. Actual result: 2010 · 148 minutes · Christopher Nolan.')
update(20, 'R5 · One person, multiple roles and questions', 'The screenshot filters Nolan: Director, Writer and Producer in Inception',
       'The complete Inception contribution query returns twenty-five records: twenty-one actors, one director, one writer and two producers. The screenshot filters Christopher Nolan and therefore shows only three rows. Those three rows are not the total contribution count. Other queries return eight sampled Nolan films, four Inception production companies and seven recorded Godfather awards. Additional questions reuse the graph and model without a separate manually populated result table. Download results exports the current result. Query files and execution reports make these counts reproducible.',
       cards=[['25 records','All Inception contributions; the image shows only Nolan.'],['8 / 4 / 7','Nolan films / Inception companies / Godfather awards.'],['14 Web samples / 24 files','Hierarchy requires schema; inferred types require --reasoned.']])
update(21, 'R5 · Endpoint, terminal and inferred types', 'Same Nolan query: one asserted type → three with saved inference',
       'The project provides GET/POST endpoint and terminal interfaces in addition to the Web application. SELECT and ASK return JSON; CONSTRUCT and DESCRIBE return Turtle. The endpoint loads the asserted graph by default. query.py --reasoned also loads the schema and inferred_classes.ttl. Query 24 returns Person in asserted mode, and Person, Filmmaker and AwardWinner with inference. reason.py creates the saved types beforehand; querying does not rerun reasoning. Hierarchy query 13 requires the schema. Actor and Filmmaker queries have LIMIT 20, while full totals are 769 and 89. Capture Nolan’s asserted Types or clearly label a genuine inferred view.',
       rows=[['Asserted graph','dbo:Person'],['With inference','Person + Filmmaker + AwardWinner']])
update(22, 'Validating data, application and publication', 'Execution evidence is stored in evidence/',
       'Validation checks film names, provenance, external links and contribution fields. All 76 source hashes match and all 24 query files execute in their appropriate graph mode. Fourteen tests and nine browser checks pass, covering endpoint behavior, Comunica, syntax errors, ASK, CONSTRUCT, IRI pages and mobile layout. Sixteen production query checks also pass. Eight public URLs are accessible without authentication; four checked RDF graphs are isomorphic to local graphs. HermiT and Pellet confirm consistency and no unsatisfiable named classes. OWL, Turtle and JSON-LD share millisecond timestamps. Tests and hashes do not establish the truth of every real-world claim.',
       image='evidence/screenshots/13_validation_en.png',
       checks=[['76/76','Matching source hashes'],['24','Query files executed'],['14 + 9','Tests + browser checks'],['8 URLs / 4 graphs','Public HTTP 200 / graph match']])
update(23, 'Assessment and limitations', 'Evidence for 5/5 requirements · 10/10 is a proposed self-score',
       'The assignment does not specify weights, so the team proposes two points per requirement. Ontology, collection, publication, external links and SPARQL interfaces each have evidence, giving a proposed ten out of ten rather than an official grade. Limitations remain: a selected thirty-film sample, label-based genre and award grouping, and no budget or streaming data. HermiT and Pellet confirm consistency, but the two cardinality classes still have zero DL-inferred instances, compared with application counts of thirty and six. SQL can answer many questions with joins, views and rules. The Semantic Web contribution is shared identifiers, reusable vocabulary, cross-dataset links, provenance and explicit definitions.',
       rows=[['R1','Ontology + OWL + tests','2/2'],['R2','76 sources + hashes + reproducibility','2/2'],['R3','Public RDF matches local data','2/2'],['R4','1,727 published identity links','2/2'],['R5','Web / endpoint / terminal','2/2']],
       cards=[['Data limitations','Selected 30-film sample; label-based groups.\nHashes ≠ truth; budget/streaming data absent.'],['Reasoning limitations','12 OWL RL classes; 2 IRI-counting rules.\nHermiT/Pellet: consistent; threshold classes: 0.'],['Semantic Web value','Shared IRIs, vocabulary, links and provenance.\nSQL can also answer many of these questions.']])
update(24, 'Conclusion and pending Protégé evidence', '24 slides · five-page report · four-minute-fifty-second demo',
       'MovieLOD connects a domain model, real source data, provenance, RDF, external links and queries in one application. This twenty-four-slide deck supports an eighteen-to-twenty-two-minute presentation or a shorter selection of key slides. Before submission, fill in team details and add genuine Protégé screenshots using the listed codes. Vietnamese instructions remain in the empty slots. No fabricated Protégé screenshots have been inserted. Images can be added directly in PowerPoint or saved with the expected filenames in evidence/protege before regenerating the deck. The demo video remains unchanged. Thank you; we welcome questions.',
       footer='Screenshot slots are placeholders, not captured evidence. Full English narration is in Speaker Notes.')

assert len(SLIDES) == 24
