"""English academic report: fifteen planned pages, backed by project evidence."""
def p(text): return {'type':'paragraph','text':text}
def h(text): return {'type':'heading','text':text}
def image(path,caption,width=16,max_height=7): return {'type':'image','path':path,'caption':caption,'width':width,'max_height':max_height}
def table(headers,rows,widths=None,caption=None): return {'type':'table','headers':headers,'rows':rows,'widths':widths,'caption':caption}
def code(text): return {'type':'code','text':text}

PAGES=[
{'title':'Cover','kind':'cover','blocks':[]},
{'title':'TABLE OF CONTENTS','kind':'toc','blocks':[]},
{'title':'1. INTRODUCTION AND OBJECTIVES','blocks':[
 h('1.1 Abstract and problem statement'),
 p('MovieLOD combines Wikidata and DBpedia responses with an OWL ontology, RDF publication, external identity links and three query interfaces. Its selected sample contains 30 films, 42 declared classes, 19,339 data triples and 1,727 identity links. Source integrity and query behavior are verified; HermiT and Pellet confirm consistency and matching inferred populations. Application counting is distinguished from OWL DL inference. The motivating problem is that movie information uses different identifiers and overlapping roles across sources. Inception and Christopher Nolan illustrate how one person can direct, write and produce the same film without losing the identity or provenance of each contribution.'),
 h('1.2 Research objectives and competency questions'),
 table(['ID','Competency question','Knowledge required'],[['CQ1','Who directed a film?','Film, Person and director relation'],['CQ2','Which roles did one person hold?','Person–film–role association'],['CQ3','How are films grouped by genre?','Genre taxonomy and film membership'],['CQ4','Which external entities identify a film?','Identity alignment across datasets'],['CQ5','Which types follow from stated facts?','Class definitions and entailment']],[1.5,7.6,6.9], 'Table 1. Competency questions guiding ontology design and evaluation.'),
 h('1.3 Scope and evaluation approach'),
 p('The selected sample is a case study rather than a comprehensive film catalogue. Evaluation examines whether the conceptual model represents the domain coherently and answers the competency questions. Three levels are distinguished: source assertions, logically entailed types, and application-defined aggregation. This distinction permits a meaningful assessment of semantic expressiveness without treating the sample as representative of the entire film industry.')
]},
{'title':'2. CONCEPTUAL FRAMEWORK','blocks':[
 image('docs/report_images/academic_framework.png','Figure 1. Conceptual workflow: source knowledge, entity alignment, RDF assertions, ontology semantics and querying. Source: authors.',16,5.2),
 h('2.1 From heterogeneous sources to a knowledge graph'),
 p('The study combines complementary source descriptions through a common conceptual model. Entity alignment identifies which records refer to the same film or person. RDF then expresses the aligned descriptions as relationships and typed values. The ontology supplies a vocabulary and axioms that make these relationships interpretable. Semantic inference adds consequences of the axioms, while SPARQL retrieves both stated and entailed knowledge. Provenance provides a basis for interpreting where each description originated.'),
 table(['Knowledge layer','Semantic role'],[['Terminological knowledge (TBox/RBox)','Classes, properties and restrictions'],['Assertional knowledge (ABox)','Individuals, relationships and literal values'],['Entailed knowledge','Consequences of assertions and axioms']],[6.4,9.6], 'Table 2. Distinct knowledge layers used in the study.'),
 h('2.2 Representation and interpretation'),
 p('Separating the layers supports a precise interpretation of query answers. A person may be explicitly described as a Person while satisfying the definition of Filmmaker through a contribution. The additional type follows from the ontology, not a new source statement. Conversely, an aggregation over distinct RDF terms is a query operation and may not establish an OWL cardinality restriction. The framework therefore separates logical entailment from data summarization.')
]},
{'title':'3. DATA ACQUISITION AND PROVENANCE','blocks':[
 p('Wikidata entities are resolved through exact English Wikipedia sitelinks. The collector retrieves film claims and the related people, companies, awards and terms. DBpedia matches are accepted only when the resource corresponds to the expected title and is typed as a Film. This conservative rule produces 28 DBpedia film links; missing matches are not guessed [4,5].'),
 table(['Claim group','Wikidata properties'],[['People and roles','P57 director; P161 cast; P58 writer; P162 producer'],['Film context','P136 genre; P495 country; P364 language'],['Dates, runtime and organizations','P577 release; P2047 runtime; P166 award; P272 company']],[5.3,10.7], 'Table 3. Main source properties used by the collector.'),
 image('docs/report_images/05_source_viewer.png','Figure 2. Actual saved response metadata and selected Inception claims. Source: supplied slide PDF, p. 15.',16,6.2),
 p('Provenance associates an assertion with its source and retrieval context. The corpus contains 76 retained source responses, allowing normalized claims to be traced to their original descriptions. This is important because source content can evolve, and a later response may differ from the one used in the study. Integrity checks establish that a retained response is unchanged; they do not establish that the source claim is true. Provenance, entity matching and semantic validation therefore address different aspects of data quality.')
]},
{'title':'4. NORMALIZATION AND RDF GENERATION','blocks':[
 p('QIDs form stable local identifiers for films, people and other entities. The build step maps source claims to ontology properties, normalizes runtime units to minutes and records ambiguous or multiple values for review. Source snapshots remain available so a normalized statement can be traced back to the exact response. The current sample includes 30 films, 851 people, 1,010 contributions, 45 companies and 672 award entities.'),
 code('res:film-Q25188 a dbo:Film ;\n  ex:title "Inception" ;\n  ex:releaseYear 2010 ;\n  ex:runtimeMinutes "148.0"^^xsd:decimal ;\n  dbo:director res:person-Q25191 .'),
 image('docs/report_images/P08_runtime_datatype.png','Figure 3. runtimeMinutes in Protégé: Film domain and xsd:decimal range. Source: supplied slide PDF, p. 16.',16,7),
 p('The representation contains 19,339 assertional triples and 518 schema triples. Turtle and JSON-LD express the same graph: their surface syntax differs, but their statements are equivalent. Datatypes distinguish a numeric duration from a textual title and permit meaningful comparison and aggregation. This also illustrates the distinction between an entity and its attributes: Nolan is identified by an IRI, whereas 148 minutes is a literal value. Normalization supports semantic interoperability by representing comparable quantities in a common unit [6].')
]},
{'title':'5. ONTOLOGY STRUCTURE','blocks':[
 p('The ontology declares 42 named classes organized around films, agents, contributions, genres, awards and contextual information. dbo:Film, dbo:Person and dbo:Country reuse DBpedia vocabulary; 39 declarations express concepts specific to the study. Vocabulary reuse supports interoperability, while local definitions address modeling requirements that a general film description does not capture. Human-readable labels and comments clarify intended meaning without replacing formal axioms.'),
 image('docs/report_images/P01_film_hierarchy.png','Figure 4. Asserted Film hierarchy and reused DBpedia Film IRI. Source: supplied slide PDF, p. 6.',16,7.5),
 table(['Concept group','Declared classes'],[['CreativeWork / Film; Agent / Person / Organization','11; 8'],['Contribution / roles; Genre; Award','6; 8; 5'],['Country / Language / SourceSnapshot / Dataset','4']],[12.3,3.7], 'Table 4. Six conceptual groups, totaling 42 declared classes.'),
 p('Film subclasses include FeatureFilm, AnimatedFilm and DocumentaryFilm, together with genre-based and award-based classes. The P31 mapping yields 29 FeatureFilm and one AnimatedFilm in this sample. DocumentaryFilm has no instances. Actor and Filmmaker overlap by design; Person and Organization represent different categories of agent. Genre and award subgroups are mapped from source-label keywords and require review when the dataset is expanded.')
]},
{'title':'6. CONTRIBUTION MODEL','blocks':[
 p('Contribution represents a person-film-role association. contributionBy identifies the person, contributionTo the film, and hasRole one of four role individuals: DirectorRole, ActorRole, WriterRole or ProducerRole. Separate records preserve multiple roles without inventing a combined profession class. Nolan’s directing, writing and producing contributions to Inception are therefore three records, not three people.'),
 image('docs/report_images/P04_contribution_restrictions.png','Figure 5. ActingContribution definition and inherited Contribution restrictions. Source: supplied slide PDF, p. 9.',16,7.4),
 table(['Inception role','Contribution records'],[['Actor','21'],['Director / Writer / Producer','1 / 1 / 2'],['Total','25']],[10.5,5.5], 'Table 5. Role distribution returned by the full Inception query.'),
 p('The contribution node represents a ternary association through three binary relations. Compared with a direct director or starring edge, it makes the person–film–role context explicit and permits association-level provenance. The additional nodes increase representation size but support extensions such as credit order or role-specific dates. Inverse relationships enable navigation from either a person or a film. The 1,010 contribution records must therefore be interpreted as contextual associations, not 1,010 distinct people.')
]},
{'title':'7. PROPERTIES AND OWL CONSTRAINTS','blocks':[
 p('The model declares 23 object properties and six data properties. Object properties connect entities, whereas data properties connect individuals to typed values. contributionBy, contributionTo and hasRole are functional and have qualified exactly-one restrictions. Universal restrictions constrain the types of their fillers. Together, these axioms characterize a Contribution as an association with one person, one film and one role, rather than an unrestricted collection of relationships.'),
 image('docs/report_images/P05_object_property.png','Figure 6. contributionBy: functional, inverse hasContribution, domain Contribution and range Person. Source: supplied slide PDF, p. 10.',16,7.1),
 table(['Data property','Datatype'],[['title; sha256','xsd:string'],['releaseYear; runtimeMinutes','xsd:integer; xsd:decimal'],['sourceUrl; retrievedAt','xsd:anyURI; xsd:dateTime']],[8.4,7.6], 'Table 6. All six declared data properties.'),
 p('OWL interprets restrictions semantically. Domain and range can support type inference, while absence of a statement does not imply its negation. Different identifiers are not automatically different individuals. Thus, an exactly-one restriction is not equivalent to requiring a filled database field. Disjointness expresses incompatibility between categories, while equivalent-class definitions characterize membership using intersections, unions, existential restrictions and fixed values. These distinctions determine which conclusions are justified [1].')
]},
{'title':'8. PUBLICATION AND FOUR-STAR DATA','blocks':[
 p('MovieLOD publishes RDF using HTTP IRIs and a CC BY-SA 4.0 data license. Turtle and JSON-LD are open serializations of the same graph; CSV is provided for convenience but is not itself RDF. The four-star claim depends on public access, an open license and useful descriptions reached through identifiers, rather than the existence of local files alone [3].'),
 image('docs/report_images/P09_inception_individual.png','Figure 7. Inception individual: types, external identity links, companies, provenance and typed literals. Source: supplied slide PDF, p. 18.',16,7.3),
 p('An IRI description connects the identity of a resource with information about it. For Inception, the description includes its types, title, duration, director, contributions, contextual entities and source associations. Human-readable presentation and machine-readable RDF serve complementary audiences. Consumers can follow these relationships to explore connected resources rather than treating a film as an isolated record.'),
 p('The academic significance of publication is interoperability: another consumer can interpret the identifiers and reuse the statements without adopting the original application. An open license establishes reuse conditions, while standard RDF representations preserve meaning across tools. External links extend this principle across datasets. Publication alone does not guarantee semantic accuracy; the quality of the model, matching decisions and source claims remains essential.')
]},
{'title':'9. EXTERNAL IDENTITY LINKS','blocks':[
 p('Entity alignment yields 1,699 Wikidata and 28 DBpedia owl:sameAs statements, totaling 1,727 identity links. These concern films, people and related entities; the film-only query returns 58 links. Matching combines identifiers, exact title associations and compatible entity types. This conservative approach prioritizes justified identity assertions over maximizing the number of links.'),
 image('docs/report_images/04_lod_levels.png','Figure 8. Cumulative Linked Open Data levels and project evidence. Source: supplied slide PDF, p. 17.',16,5),
 code('res:film-Q25188 owl:sameAs\n  <http://www.wikidata.org/entity/Q25188>,\n  <http://dbpedia.org/resource/Inception> .'),
 p('sameAs means that identifiers denote the same entity. It differs from reusing dbo:Film as vocabulary and from sourceSnapshot as provenance. Identity links require careful matching because reasoning can propagate statements across aliases. The application therefore filters local resource namespaces when counting inferred instances, preventing Wikidata and DBpedia aliases from inflating totals.'),
 table(['Measure','Recorded result'],[['All identity links','1,727'],['Wikidata / DBpedia links','1,699 / 28'],['Film-only link query','58 rows']],[10.8,5.2], 'Table 7. Link counts and their scopes.')
]},
{'title':'10. SPARQL AND COMPETENCY QUESTIONS','blocks':[
 p('SPARQL operationalizes the competency questions through graph patterns. SELECT retrieves bindings, ASK evaluates whether a pattern has a solution, and CONSTRUCT creates a graph from matching data [2]. In the Inception example, the query joins the film’s title and director relationship with the person’s label. OPTIONAL permits a result even when a descriptive attribute is absent.'),
 image('docs/report_images/06_query_ui.png','Figure 9. Inception query on the actual application. Source: supplied slide PDF, p. 19.',16,6.8),
 table(['Question','Verified result'],[['Inception year / runtime / director','2010 / 148 min / Christopher Nolan'],['Nolan films; Inception companies','8 films; 4 companies'],['Inception actors; Godfather awards','21 actors; 7 awards']],[8,8], 'Table 8. Selected query outputs.'),
 p('The query examples demonstrate structural expressiveness: one pattern retrieves a film’s attributes, another follows contributions to roles, and an aggregation summarizes films by genre. Taxonomic queries can use subclass relationships to retrieve broader categories. Answers depend on the knowledge considered: asserted Person membership differs from entailed Filmmaker membership. LIMIT restricts displayed solutions rather than the population of a class. A useful interpretation of an answer therefore states its graph scope and counting unit.')
]},
{'title':'11. REASONING AND INTERPRETATION','blocks':[
 p('Reasoning evaluates whether the assertions and axioms admit a consistent interpretation and determines additional class memberships. Independent classification with HermiT and Pellet found the knowledge base consistent and no named class unsatisfiable. Both reasoners agreed on the populations reported below. This agreement supports the interpretation of the model; it is not evidence that every source claim is factually correct.'),
 image('docs/report_images/P06_filmmaker_equivalent_class.png','Figure 10. Filmmaker equivalent-class definition in an asserted Protégé view. Source: supplied slide PDF, p. 13. This image shows the axiom, not reasoner execution.',16,6.5),
 table(['Class group','HermiT / Pellet result'],[['Actor; Filmmaker; AwardWinner','769; 89; 290'],['Acting / Directing / Writing / ProducingContribution','855 / 31 / 51 / 73'],['Action / Comedy / Drama / ScienceFiction / AwardWinningFilm','12 / 4 / 25 / 6 / 26'],['MultiGenreFilm; FilmStudio','0; 0 DL-inferred instances']],[10.2,5.8], 'Table 9. Local instance counts independently confirmed by both reasoners.'),
 p('Nolan satisfies Filmmaker through a directing, writing or producing contribution and AwardWinner through an award association. Twelve populations agree with OWL RL classification. In contrast, distinct-IRI aggregation identifies 30 MultiGenreFilm and six FilmStudio candidates, while neither DL reasoner entails those memberships under the current axioms. The discrepancy reflects different identity assumptions, not a contradictory result. Absence of inferred instances does not imply that a class is unsatisfiable.')
]},
{'title':'12. EVALUATION AND LIMITATIONS','blocks':[
 p('Evaluation considers representational coverage, logical consistency and the ability to answer competency questions. The 30-film sample contains a year, duration and director for every film. Contribution records preserve multiple roles, and query results distinguish role associations from distinct people. The genre and award taxonomies support category-based retrieval. These observations demonstrate capabilities within the sample, rather than general accuracy over the film domain.'),
 image('docs/report_images/P03_genre_award_hierarchy.png','Figure 11. Genre hierarchy supporting category-based retrieval. Source: supplied slide PDF, p. 8.',16,5.6),
 table(['Dimension','Observation','Interpretation'],[['Completeness','30/30 films; 3 attributes','Coverage within the selected sample'],['Consistency','Agreement of two reasoners','No detected logical contradiction'],['Expressiveness','Roles, hierarchy and identity','Competency questions are answerable'],['External validity','Selected 30-film corpus','Industry-wide conclusions are unsupported']],[3.7,5.1,7.2], 'Table 10. Academic evaluation dimensions and their interpretive limits.'),
 p('Selection bias limits generalization, and keyword-based genre or award grouping can introduce semantic misclassification. Identity alignment also lacks an independently annotated reference set, so precision and recall are not claimed. Logical consistency is weaker than factual correctness; incomplete information remains possible under open-world semantics. A broader study should separately evaluate source accuracy, matching quality and sensitivity to modeling assumptions.')
]},
{'title':'13. CONCLUSION AND REFERENCES','blocks':[
 h('13.1 Conclusion and future work'),
 p('The study demonstrates how a movie domain can be represented as linked knowledge rather than isolated records. The Contribution pattern preserves the context of multiple roles, reused vocabulary supports interoperability, and identity links connect complementary descriptions. SPARQL answers competency questions while OWL exposes consequences of explicit definitions. The distinction between entailment and distinct-term aggregation is a central methodological result: apparently similar counts can rest on different semantic assumptions.'),
 p('Future research should use a larger and more diverse sample, annotated identity matches and expert-reviewed genre and award categories. Conflicting source claims require provenance-aware reconciliation. Richer models could distinguish film works, releases and editions. Cardinality-based membership should rely on justified individual distinctions. These extensions would permit more rigorous evaluation of accuracy, completeness and generalizability.'),
 h('13.2 References'),
 p('[1] W3C. OWL 2 Web Ontology Language Primer, Second Edition. 2012. https://www.w3.org/TR/owl2-primer/'),
 p('[2] W3C. SPARQL 1.1 Query Language. 2013. https://www.w3.org/TR/sparql11-query/'),
 p('[3] Tim Berners-Lee. Linked Data — Design Issues. W3C. https://www.w3.org/DesignIssues/LinkedData.html'),
 p('[4] Wikidata. Data access. https://www.wikidata.org/wiki/Wikidata:Data_access'),
 p('[5] DBpedia Association. SPARQL over Online Databases. https://www.dbpedia.org/resources/sparql/'),
 p('[6] W3C. RDF 1.1 Concepts and Abstract Syntax. 2014. https://www.w3.org/TR/rdf11-concepts/'),
 p('Online references accessed 8 October 2026. All figure origins are identified in their captions.')
]}
]

assert len(PAGES)==15
