PREFIX ex: <https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/ontology#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX res: <https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?s ?type WHERE {
 GRAPH <urn:movie:reasoned> { ?s a ?type }
 FILTER(STRSTARTS(STR(?s), "https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/resource/") && STRSTARTS(STR(?type), "https://movie-lod-semantic-web.laminhtrung2001.chatgpt.site/ontology#"))
 FILTER NOT EXISTS { GRAPH <urn:movie:asserted> { ?s a ?type } }
} ORDER BY ?type ?s
